DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE PRODUCTS(
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  price VARCHAR(250) NOT NULL,
  weight VARCHAR(250) NOT NULL,
  description VARCHAR(250),
  stock VARCHAR(250)
);

/**
CREATE TABLE IF NOT EXISTS PRODUCTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  price VARCHAR(250) NOT NULL,
  weight VARCHAR(250) NOT NULL,
  description VARCHAR(250),
  stock VARCHAR(250)
);
**/
