######################## default configuration ####################
baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Jasmin sweets'
theme = 'hargo'

############################## navigation ###############################
[menu]
[[menu.main]]
  name = "Products"
  URL = "products"
  weight = 1

  [[menu.main]]
  name = "Blog"
  URL = "blog"
  weight = 2

  [[menu.main]]
  name = "FAQ"
  URL = "faq"
  weight = 3

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 4