name: Deployment Workflow

on:
  push:
    branches: 
      - master

jobs:
  deploy:
    name: Deployment Workflow
    runs-on: ubuntu-latest
    steps: 
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2.3.1
        with: 
          key: ${{ secrets.SSH_PRIVATE_KEY }}  
      
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
        
      - name: Copy files to server
        script: |
          cd /var/www/html
          git pull origin master
          git status
          