name: Deployment Workflow
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deployment Workflow
    runs-on: ubuntu-latest

    steps: 
    - name: install ssh key
      uses: caberger/install-ssh-key@v1.0
      with:
        ssh-private-key:  ${{ secrets.SSH_PRIVATE_KEY }}
        user: ${{ secrets.SERVER_USER }}
        server: ${{ secrets.SERVER }}
        alias: server
    
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        # extended: true
    
    - name: build Hugo website
      run: |
        pwd
        ls -l
        hugo
      working-directory: Website/jasminsweets_ws 
    
    - name: test ssh
      run: |
        ssh server ls -l
        



