name: Deployment (dev)

on:
  push:
    branches:
      -master

jobs:
  deploy:
    name: Deployment (dev)
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v1

      - name: Node 12.16.3
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.3
      - name: npm install and npm run build
        run: |
          npm i
          npm run build
      
      - name: copy files to server
        uses: appleboy/scp-action@master
        with: 
          HOST: ${{ secrets.HOST }}
          PORT: ${{ secrets.PORT }}
          USUERNAME: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          target: ${{ secrets.TARGET }}
          source: "./Website/jasminsweets_ws/public*" 
          strip_components: 1 
